<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Messages extends MX_Controller{
    function __construct()
    {
        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->model('Messages_model');
    } 

    /*
     * Listing of messages
     */
    function index()
    {
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $groupId = $_SESSION['groupId'];

        $this->load->library('pagination');
        
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $groupId == 0 ? $config['base_url'] = site_url('index.php/administrator/messages') : $config['base_url'] = site_url('index.php/manager/messages');
        $config['total_rows'] = $this->Messages_model->get_all_messages_count();
        $this->pagination->initialize($config);

        $data['messages'] = $this->Messages_model->get_all_messages($params);
        
        $data['content'] = $this->load->view('messages/index',$data,true);
        $groupId == 0 ? $this->parser->parse(TEMPLATE.'/content_admin', $data) : $this->parser->parse(TEMPLATE.'/content_manager', $data);
    }

    /*
     * Adding a new messages
     */
    function add()
    {   
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }

        $username = $_SESSION['nik'];
        $groupId = $_SESSION['groupId'];

        $this->load->library('form_validation');

		$this->form_validation->set_rules('messages','messages','required|max_length[500]');
		
        
		if($this->form_validation->run()){
            
            $params = array(
                'message' => $this->input->post('messages'),
                'allocation_message'=> $this->input->post('allocationMessage'),
                'created_by'=> $username
            );
            $user_id = $this->Messages_model->add_message($params); 
            $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Data Saved!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
            $groupId === 0 ? redirect('index.php/administrator/messages') : redirect('index.php/manager/messages');
            ;
        }
        else {
            $data['content'] = $this->load->view('messages/add',null,true);
            $groupId == 0 ? $this->parser->parse(TEMPLATE.'/content_admin', $data) : $this->parser->parse(TEMPLATE.'/content_manager', $data);
        }
    }  

    
    /*
     * Deleting messages
     */
    function remove($id)
    {
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }

       $groupId = $_SESSION['groupId'];
       $message = $this->Messages_model->get_message($id);

       if(isset($message['id_message'])) {
            $params = array(
                'action_delete' => '1',
            );

            $this->Messages_model->update_messages($id,$params);
            $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Data Has been remove !
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button></div>');

            $groupId === 0 ? redirect('index.php/administrator/messages') : redirect('index.php/manager/messages');
            
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
