<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Messages_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get message by id
     */
    function get_message($id)
    {
        return $this->db->get_where('dt_messages',array('id_message'=>$id))->row_array();
    }
    
    /*
     * Get all messages count
     */
    function get_all_messages_count()
    {
        $this->db->from('dt_messages');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all messages
     */
    function get_all_messages($params = array())
    {
        $this->db->select('*');
        $this->db->from('dt_messages');
        $this->db->where('action_delete','0');
        $this->db->order_by('created_date', 'DESC');

        $query = $this->db->get();
       
        if(isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }

       return $query->result();
    }
        
    /*
     * function to add new dt_messages
     */
    function add_message($params){
        $this->db->insert('dt_messages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to delete message
     */

    function update_messages($id,$params)
    {
        $this->db->where('id_message',$id);
        return $this->db->update('dt_messages',$params);
    }
    
    

}
